// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2JIDGo1c3nnxQSnbnlWFxzKvmIe7RNvo',
    appId: '1:381271821335:web:39075b1b65dfbf24786052',
    messagingSenderId: '381271821335',
    projectId: 'tasky-admin-dashboard',
    authDomain: 'tasky-admin-dashboard.firebaseapp.com',
    storageBucket: 'tasky-admin-dashboard.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzoOvid5wi0672MsadedOCv5o03cT-cco',
    appId: '1:381271821335:android:65b9efdf2d1e538c786052',
    messagingSenderId: '381271821335',
    projectId: 'tasky-admin-dashboard',
    storageBucket: 'tasky-admin-dashboard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaG_xa7rQYesZ5bpC3fuZO7b-f7_7KTHQ',
    appId: '1:381271821335:ios:e5cc98eb1069e06c786052',
    messagingSenderId: '381271821335',
    projectId: 'tasky-admin-dashboard',
    storageBucket: 'tasky-admin-dashboard.appspot.com',
    iosBundleId: 'com.example.taskyAdminDashboard',
  );
}
